import type { CertificateTemplate, FieldDef, Segment } from "../types";

// Format xii — Independent Auditor's Certificate on half-yearly compliances with
// Covenants (debentures), for submission to the Debenture Trustee (Annexure III).
// The largest format. Locked wording transcribed verbatim from the source PDF
// (pages 100–109). Run `npm run verify:certs -- --only xii-half-yearly`.
//
// The covenant statements (Annexure / Statement I / Statement II) are deeply nested,
// mostly-blank fill-in tables in the illustrative format. They are modelled here as
// simple scaffold tables (Clause / Covenant / Management-comment columns) — a nested /
// merged-cell table type is the proper production model. See notes.

const pair = (firm: string, individual: string) => [
  { value: "firm", label: firm, fragment: firm },
  { value: "individual", label: individual, fragment: individual },
];
const col = (key: string, label: string) => ({ key, label, numeric: false });
const covenantCols = [col("clause", "Clause no."), col("covenant", "Covenants"), col("comments", "Management Comments on compliance status")];

const fields: FieldDef[] = [
  { key: "companyName", label: "Company name", type: "text", required: true, repeatKey: "COMPANY" },
  { key: "companyRegdOffice", label: "Registered office address", type: "textarea", required: true },
  { key: "debentureTrusteeName", label: "Name of the Debenture Trustee", type: "text", required: true, repeatKey: "TRUSTEE" },
  { key: "fyEndYear", label: "Half-year-end year (fills 'March 31, 20XX')", type: "year", required: true, repeatKey: "FYEND" },
  { key: "fyStartYear", label: "EBITDA period start year (fills 'April 01, 20XX')", type: "year", required: true },
  { key: "n1Debentures", label: "N1 — debentures (tranche 1 descriptor)", type: "text", required: true, repeatKey: "N1" },
  { key: "n2Debentures", label: "N2 — debentures outstanding (descriptor)", type: "text", required: true, repeatKey: "N2" },
  { key: "n3Debentures", label: "N3 — debentures (tranche 2 descriptor)", type: "text", required: true, repeatKey: "N3" },
  { key: "infoMemoDate", label: "Information Memorandum date", type: "date", required: true },
  { key: "placementMemoDate", label: "Placement Memorandum date", type: "date", required: true },
  { key: "trustDeedDate", label: "Debenture Trust Deed date", type: "date", required: true, repeatKey: "DEED" },
  { key: "covenantSchedule", label: "Schedule reference (covenants)", type: "text", required: true, repeatKey: "SCHED" },
  { key: "covenantClause", label: "Clause reference (covenants)", type: "text", required: true, repeatKey: "CCLAUSE" },
  { key: "covenantPart", label: "Part reference (Debenture Trust Deed)", type: "text", required: true, repeatKey: "CPART" },
  { key: "auditOpinionDate", label: "Audit (Unmodified Opinion) date (para 6)", type: "date", required: true },
  { key: "duePeriod", label: "Repayment 'no sums due' period (para 8d)", type: "text", required: true, help: "e.g. 1 October 2024 to 31 March 2025" },
  { key: "engagementLetterDate", label: "Engagement letter/agreement date", type: "date", required: true },
  { key: "certificateDate", label: "Certificate date", type: "date", required: true, repeatKey: "CERTDATE" },

  { key: "signerType", label: "Signing as", type: "enumToggle", required: true, options: [
    { value: "firm", label: "Firm", fragment: "" },
    { value: "individual", label: "Individual", fragment: "" },
  ] },
  { key: "sg_iwe", label: "", type: "enumToggle", deriveFrom: "signerType", options: pair("we", "I") },
  { key: "sg_iweCap", label: "", type: "enumToggle", deriveFrom: "signerType", options: pair("We", "I") },
  { key: "sg_myour", label: "", type: "enumToggle", deriveFrom: "signerType", options: pair("our", "my") },
  { key: "sg_myourCap", label: "", type: "enumToggle", deriveFrom: "signerType", options: pair("Our", "My") },
  { key: "sg_meus", label: "", type: "enumToggle", deriveFrom: "signerType", options: pair("us", "me") },

  { key: "firmName", label: "Firm name (above 'Chartered Accountants')", type: "text", required: true },
  { key: "firmRegistrationNumber", label: "Firm Registration Number (FRN)", type: "text", required: true },
  { key: "memberName", label: "Name of the member signing", type: "text", required: true },
  { key: "designation", label: "Designation (Partner / Proprietor)", type: "text", required: true },
  { key: "membershipNo", label: "Membership No.", type: "text", required: true },
  { key: "placeOfSignature", label: "Place of signature", type: "text", required: true },
  { key: "udin", label: "UDIN (paste from ICAI portal — never generated)", type: "udin", required: true, validate: "udin" },

  { key: "statement1Table", label: "Statement I — Covenants (Debenture Trust Deed + Information Memorandum)", type: "table", table: {
    rowLabels: ["A. Amount of debentures / covenant to pay principal and interest", "B. Negative Covenants", "C. Information Covenants", "Information Memorandum — Ownership Covenant"],
    columns: covenantCols,
  } },
  { key: "statement2Table", label: "Statement II — Covenants (Placement Memorandum)", type: "table", table: {
    rowLabels: ["A. Covenants to pay Principal and Interest (3.1)", "Covenant to pay obligations (3.2)"],
    columns: covenantCols,
  } },
];

const f = (key: string): Segment => ({ kind: "field", key });
const t = (text: string): Segment => ({ kind: "text", text });
// debenture descriptor line shared by the subject/enclosures/statements
const nccb = "listed, rated, unsecured, redeemable, non-convertible debentures";

const segments: Segment[] = [
  t("To\nThe Board of Directors\n"),
  f("companyName"),
  t("\n"),
  f("companyRegdOffice"),

  t("\n\nIndependent Auditor's Certificate on half yearly compliances with Covenants as at March 31, "),
  f("fyEndYear"),
  t(" for submission to "),
  f("debentureTrusteeName"),
  t(` (hereinafter referred as the "Debenture Trustee")`),

  t("\n\n1. This Certificate is issued in accordance with the terms of "),
  f("sg_myour"),
  t(" engagement letter/agreement dated "),
  f("engagementLetterDate"),
  t("."),

  t("\n\n2. "),
  f("sg_iweCap"),
  t(" have been requested by the management/ Board of Directors of "),
  f("companyName"),
  t(` (hereinafter the "Company")having its registered office at `),
  f("companyRegdOffice"),
  t(" to certify the accompanying statement containing compliances with the covenants for:\na) "),
  f("n1Debentures"),
  t(" "),
  f("n2Debentures"),
  t(` ${nccb} as at March 31, `),
  f("fyEndYear"),
  t(` (hereinafter referred to as "the Statement I"), prepared by the Company as per the Information Memorandum dated `),
  f("infoMemoDate"),
  t(" and Debenture Trust Deed dated "),
  f("trustDeedDate"),
  t(` (hereinafter referred to as "the Information Memorandum and Debenture Trust Deed").\nb) `),
  f("n3Debentures"),
  t(` ${nccb} as at March 31, `),
  f("fyEndYear"),
  t(` (hereinafter referred to as "the Statement II"), prepared by the Company as per the Placement Memorandum dated `),
  f("placementMemoDate"),
  t(" and Debenture Trust Deed dated "),
  f("trustDeedDate"),
  t(` (hereinafter referred to as "the Placement Memorandum and Debenture Trust Deed").\n\n('Annexure', 'Statement I' and 'Statement II' hereinafter collectively referred to as "the Statements") from the Audited Standalone and Consolidated Financial Statements of the Company and other relevant records and documents maintained by the Company as at and for the half year ended March 31, `),
  f("fyEndYear"),
  t(".\n\nThis Report is required by the Company for the purpose of submission to "),
  f("debentureTrusteeName"),
  t(` (hereinafter referred as the "Debenture Trustee"), of the Company which has been initialled by `),
  f("sg_meus"),
  t(" for identification purposes only."),

  t("\n\nManagement's Responsibility\n\n3. The Management of the Company is responsible for the preparation of the said Statements including the preparation and maintenance of all accounting and other relevant supporting records and documents. This responsibility includes the design, implementation, and maintenance of internal controls relevant to the preparation and presentation of the said Statements and applying an appropriate basis of preparation and making estimates that are reasonable in the circumstances. The Management of the Company is also responsible to comply with the Regulations."),

  t("\n\n4. The Management of the Company is also responsible for ensuring that the Company complies with all the relevant requirements of SEBI (Listing Obligations and Disclosure Requirements) Regulations 2015, the Companies Act 2013 and for providing all relevant information to the Debenture Trustee and for complying with all the covenants as prescribed in the Information Memorandum, Placement Memorandum and Debenture Trust Deed entered into between the Company and the Debenture Trustee."),

  t("\n\nAuditor's Responsibility\n\n5. It is "),
  f("sg_myour"),
  t(" responsibility to provide limited assurance as to whether:\na) for "),
  f("n1Debentures"),
  t(""),
  f("n2Debentures"),
  t(` ${nccb}, the Company is in compliance with all the covenants mentioned in the `),
  f("covenantSchedule"),
  t(" Schedule "),
  // source: "… Schedule [refer to the Schedule] and Clause …" — the bracketed hint falls
  // in the gap between these two locked segments.
  t("and Clause "),
  f("covenantClause"),
  t(" of Part "),
  f("covenantPart"),
  t(" of the Debenture Trust Deed and the financial information, negative and ownership covenants mentioned in Clause "),
  f("covenantClause"),
  t(` of the Information Memorandum as on March 31, `),
  f("fyEndYear"),
  t(` (herein after referred to as "the said covenants").\nb) for `),
  f("n3Debentures"),
  t(` ${nccb}, the Company is in compliance with all the covenants mentioned in the `),
  f("covenantSchedule"),
  t(" Schedule "),
  // source: "… Schedule [refer to the Schedule] and Clause …" — the bracketed hint falls
  // in the gap between these two locked segments.
  t("and Clause "),
  f("covenantClause"),
  t(" of Part "),
  f("covenantPart"),
  t(" of the Debenture Trust Deed and the financial information, negative and ownership covenants mentioned in Clause "),
  f("covenantClause"),
  t(" of the Placement Memorandum as on March 31, "),
  f("fyEndYear"),
  t(` (hereinafter referred to as "the said covenants").`),

  t("\n\n6. "),
  f("sg_iweCap"),
  t(" have performed audit of the standalone and consolidated Ind-AS financial statements of the Company for the year ended March 31, "),
  f("fyEndYear"),
  t(" prepared by the Company pursuant to the requirements of Regulation 33 and Regulation 52(4) read with Regulation 63 of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015, as amended and have issued an Unmodified Opinion dated "),
  f("auditOpinionDate"),
  t(". "),
  f("sg_myourCap"),
  t(` audit of these financial statements was conducted in accordance with the Standards on Auditing, as specified under Section 143(10) of the Companies Act, 2013 and other applicable authoritative pronouncements issued by the Institute of Chartered Accountants of India ("ICAI"). These standards require that `),
  f("sg_iwe"),
  t(" plan and perform the audit to obtain reasonable assurance as to whether the financial statements are free of material misstatement."),

  t("\n\n7. "),
  f("sg_myourCap"),
  t(" scope of work did not involve "),
  f("sg_meus"),
  t(" performing audit tests for the purpose of expressing an opinion on the fairness or accuracy of any of the financial information or the financial results of the Company taken as a whole. "),
  f("sg_iweCap"),
  t(" have not performed an audit, the objective of which would be the expression of an opinion on the financial results, specified elements, accounts or items thereof, for the purpose of this report. Accordingly, "),
  f("sg_iwe"),
  t(" do not express such an opinion."),

  t("\n\n8. A limited assurance engagement includes performing procedures to obtain sufficient appropriate evidence on the applicable criteria mentioned in paragraph 5 above. The procedures performed vary in nature and timing from, and are less extent than for, a reasonable assurance. Consequently, the level of assurance obtained is substantially lower than the assurance that would have been obtained had a reasonable assurance engagement been performed. Accordingly, "),
  f("sg_iwe"),
  t(" have performed the following procedures in relation to compliance with covenants (including financial, informative and negative covenants):\na) Obtained and verified the computation of Net Debt/Equity, Net Debt/EBITDA, Net Assets/Total Debt from the audited standalone and Net Debt/Equity from the audited consolidated financial statements of the Company as at March 31, "),
  f("fyEndYear"),
  t(".\nb) Obtained and verified the computation of earnings before interest expense, tax, depreciation and amortization (EBITDA) for the year April 01, "),
  f("fyStartYear"),
  t(" to March 31, "),
  f("fyEndYear"),
  t(".\nc) Obtained and verified the credit rating from the communication received by the Company from Investment Information and Credit Rating Agency (ICRA).\nd) Verified the repayment schedule from the Debenture Trust Deed and noted that no sums were due for the period from "),
  f("duePeriod"),
  t(".\ne) With respect to the said covenants, other than those mentioned above, "),
  f("sg_iwe"),
  t(" have relied on the management representation and confirmation that the Company has complied with all these covenants as on March 31, "),
  f("fyEndYear"),
  t(" and "),
  f("sg_iwe"),
  t(" have not performed any independent procedures in this regard.\nf) Performed necessary inquiries with the Management and obtained necessary representations."),

  t("\n\n9. "),
  f("sg_iweCap"),
  t(" conducted "),
  f("sg_myour"),
  t(" examination in accordance with the Guidance Note on Reports or Certificates for Special Purposes issued by the ICAI. The Guidance Note requires that "),
  f("sg_iwe"),
  t(" comply with the ethical requirements of the Code of Ethics issued by the ICAI."),

  t("\n\n10. "),
  f("sg_iweCap"),
  t(" have complied with the relevant applicable requirements of the Standard on Quality Control (SQC) 1, Quality Control for Firms that Perform Audits and Reviews of Historical Financial Information, and Other Assurance and Related Services Engagements."),

  t("\n\nConclusion\n\n11. Based on the procedures performed by "),
  f("sg_meus"),
  t(", as referred to in paragraph 8 above and according to the evidence obtained and verification of books of accounts produced before "),
  f("sg_meus"),
  t(" and the information and explanations received and representation received from management of the Company, nothing has come to "),
  f("sg_myour"),
  t(" attention that causes "),
  f("sg_meus"),
  t(" to believe that the Company is not in compliance with the said covenants as on and for the half year ended March 31,"),
  f("fyEndYear"),
  t("."),

  t("\n\nRestrictions on Use\n\n12. This certificate is being solely issued at the request of the Management of the Company pursuant to the requirements of Debenture Trust Deed for submission to the Debenture Trustee. This Certificate should not be used for any other purpose or by any person other than the addressee of this Certificate. Accordingly, "),
  f("sg_iwe"),
  t(" do not accept or assume any liability or any duty of care for any other purpose or to any other person to whom this Certificate is shown or into whose hands it may come without "),
  f("sg_myour"),
  t(" prior consent in writing."),

  // Signature block (xii: "(Firm's Registration No. …)" parens, "Membership No.", "Place of Signature:")
  t("\n\nFor "),
  f("firmName"),
  t("\nChartered Accountants\n(Firm's Registration No. "),
  f("firmRegistrationNumber"),
  t(")\n\nSignature\n"),
  f("memberName"),
  t("\n"),
  f("designation"),
  t("\nMembership No. "),
  f("membershipNo"),
  t("\nPlace of Signature: "),
  f("placeOfSignature"),
  t("\nUDIN: "),
  f("udin"),
  t("\nDate: "),
  f("certificateDate"),

  // Enclosures list
  t("\n\nEnclosures: Statement comprising of:\n• Annexure of Compliance with Covenants for "),
  f("n1Debentures"),
  t(" "),
  f("n2Debentures"),
  t(" "),
  f("n3Debentures"),
  t(` ${nccb} as at and for the half year ended March 31, `),
  f("fyEndYear"),
  t("\n• Statement I - Compliance with Covenants for "),
  f("n1Debentures"),
  t(" "),
  f("n2Debentures"),
  t(` ${nccb} as at and for the half year ended March 31, `),
  f("fyEndYear"),
  t("\n• Statement II - Compliance with Covenants for "),
  f("n3Debentures"),
  t(` ${nccb} as at and for the half year ended March 31, `),
  f("fyEndYear"),

  // Annexure statement (title page — no table)
  t("\n\nStatement\nAnnexure of Compliance with Covenants for "),
  f("n1Debentures"),
  t(" "),
  f("n2Debentures"),
  t(" "),
  f("n3Debentures"),
  t(` ${nccb} as at and for the half year ended March 31, `),
  f("fyEndYear"),
  t("\nThis Statement is initialed for identification purposes only and should be read along with Certificate dated "),
  f("certificateDate"),
  t("\nSignature and stamp of the Auditor"),

  // Statement I
  t("\n\nStatement I - Compliance with Covenants for "),
  f("n1Debentures"),
  t(" "),
  f("n2Debentures"),
  t(` ${nccb} as at and for the half year ended March 31, `),
  f("fyEndYear"),
  t("\nList of Covenants as prescribed in the Debenture Trust Deed, Information Memorandum and their compliance status as at and for as the half year ended on March 31, "),
  f("fyEndYear"),
  f("statement1Table"),
  t("This Statement is initialed for identification purposes only and should be read along with Certificate dated "),
  f("certificateDate"),
  t("\nSignature and stamp of the Auditor"),

  // Statement II
  t("\n\nStatement II to the Certificate of Compliance with Covenants for "),
  f("n3Debentures"),
  t(` ${nccb} as at and for the half year ended March 31, `),
  f("fyEndYear"),
  t("\nList of Covenants as prescribed in the Debenture Trust Deed, Placement Memorandum and their compliance status as at and for as the half year ended on March 31, "),
  f("fyEndYear"),
  f("statement2Table"),
  t("This Statement is initialed for identification purposes only and should be read along with Certificate dated "),
  f("certificateDate"),
  t("\nSignature and stamp of the Auditor"),
];

export const formatXII: CertificateTemplate = {
  id: "xii-half-yearly",
  romanNo: "xii",
  title: "Independent Auditor's Certificate on half yearly compliances with Covenants (Debenture Trustee)",
  version: "2025.10.0",
  status: "enabled",
  sourcePdf: "src/lib/certificates/source/Certifications_guidebook_ICAI.pdf",
  sourcePages: [100, 109],
  hash: "44930e53218eafaceff2ffb94a52aa62c40065fbe7961456960fb021483a3994", // §6.5 — pinned after clean text pass
  verifiedBy: "Rajkumar Annamalai",
  verifiedAt: "2026-07-14",
  fields,
  segments,
  tables: ["statement1Table", "statement2Table"],
  notes: [
    "Largest format. Covenant statements (Annexure / Statement I / Statement II) are deeply nested, mostly-blank fill-in tables — modelled here as simple 3-column scaffolds (Clause / Covenant / Management-comment). A nested/merged-cell table type is the proper production model; the CA must populate per the actual Debenture Trust Deed / Information & Placement Memoranda.",
    "N1/N2/N3 debenture descriptors are free-text fields (source placeholders are long descriptors, not bare counts).",
    "Square-bracket signature label 'For [FIRM/INDIVIDUAL]' dropped; FRN uses the source's parentheses '(Firm's Registration No. <n>)'.",
    "Always 'Unmodified Opinion' + full s.143(10) clause (no company/opinion toggle); EBITDA period uses fyStartYear (April 01) + fyEndYear (March 31).",
    "Verbatim quirks kept: '(Company\")having' (no space), 'INFORMATION CONVENANTS' typo appears only in a scaffold table label, 'March 31,20XX' (no space) in para 11, 'less extent than' (para 8).",
    "firmName/firmRegistrationNumber always-required (see Format i note).",
  ],
};
