// The Excel "database" on SharePoint. Regenerated from Postgres in full — never
// appended to, so hand edits in the workbook are lost (the first row says so).
import ExcelJS from "exceljs";
import type { ClientDocType, Department, EntityType, GrowthGoal, JobStatus, TurnoverBand } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { departmentLabel } from "@/lib/ca-firm";
import { ensureFolder, getAppOnlyToken, uploadFileContent } from "@/lib/graph";
import { DOC_TYPES, ENTITY_TYPES, GROWTH_GOALS, JOB_STATUSES, TURNOVER_BANDS } from "./core";
import { clientsRoot } from "./storage";

export const WORKBOOK_PATH = () => `${clientsRoot()}/_Database/Client Database.xlsx`;
const XLSX_MIME = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
const NOTICE = "Generated by the LMS from the client database. Do not edit here — every rebuild overwrites this file.";

export type WorkbookInput = {
  clients: Array<{
    name: string; entityType: EntityType; pan: string | null; gstin: string | null; cin: string | null; industry: string | null;
    city: string | null; contactName: string | null; contactPhone: string | null; contactEmail: string | null; referralSource: string | null;
    turnover: number; turnoverBand: TurnoverBand; growthGoal: GrowthGoal; growthNote: string | null; onboardedOn: Date; handler: string;
    active: boolean; jobCount: number; lastJobOn: Date | null; folderStatus: string;
  }>;
  jobs: Array<{
    client: string; fy: string; department: Department; service: string; handler: string; status: JobStatus; dueOn: Date | null;
    fees: number | null; turnoverBand: TurnoverBand; growthGoal: GrowthGoal; entityType: EntityType; city: string | null;
    createdAt: Date; createdBy: string;
  }>;
  documents: Array<{ client: string; job: string; docType: ClientDocType; name: string; uploadedBy: string; createdAt: Date; webUrl: string }>;
};

const IST = "Asia/Kolkata";
export const istDate = (d: Date) => d.toLocaleDateString("en-CA", { timeZone: IST }); // YYYY-MM-DD
export const istMonth = (d: Date) => istDate(d).slice(0, 7);
const dateOrBlank = (d: Date | null) => (d ? istDate(d) : "");

type Cell = string | number;

function addTableSheet(wb: ExcelJS.Workbook, name: string, columns: string[], rows: Cell[][]) {
  const ws = wb.addWorksheet(name);
  ws.getCell("A1").value = NOTICE;
  ws.getCell("A1").font = { italic: true, color: { argb: "FF888888" } };
  ws.addTable({
    name: `${name}Table`,
    ref: "A2",
    headerRow: true,
    style: { theme: "TableStyleMedium2", showRowStripes: true },
    columns: columns.map((c) => ({ name: c, filterButton: true })),
    rows: rows.length ? rows : [columns.map(() => "")], // exceljs needs at least one row
  });
  columns.forEach((c, i) => { ws.getColumn(i + 1).width = Math.min(44, Math.max(12, c.length + 4)); });
  ws.views = [{ state: "frozen", ySplit: 2 }];
}

export function buildClientWorkbook(input: WorkbookInput): ExcelJS.Workbook {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Indefine LMS";
  addTableSheet(wb, "Clients",
    ["Client", "Entity type", "PAN", "GSTIN", "CIN", "Industry", "City", "Contact", "Phone", "Email", "Referral source",
      "Turnover (₹)", "Turnover band", "Growth goal", "Growth note", "Onboarded on", "Primary handler", "Active", "Jobs", "Last job on", "Folder status"],
    input.clients.map((c) => [
      c.name, ENTITY_TYPES[c.entityType], c.pan ?? "", c.gstin ?? "", c.cin ?? "", c.industry ?? "", c.city ?? "", c.contactName ?? "",
      c.contactPhone ?? "", c.contactEmail ?? "", c.referralSource ?? "", c.turnover, TURNOVER_BANDS[c.turnoverBand], GROWTH_GOALS[c.growthGoal],
      c.growthNote ?? "", istDate(c.onboardedOn), c.handler, c.active ? "Yes" : "No", c.jobCount, dateOrBlank(c.lastJobOn), c.folderStatus,
    ]));
  addTableSheet(wb, "Jobs",
    ["Client", "FY", "Month", "Department", "Service", "Handler", "Status", "Due on", "Fees (₹)", "Turnover band", "Growth goal",
      "Entity type", "City", "Created on", "Created by"],
    input.jobs.map((j) => [
      j.client, j.fy, istMonth(j.createdAt), departmentLabel(j.department), j.service, j.handler, JOB_STATUSES[j.status], dateOrBlank(j.dueOn),
      j.fees ?? "", TURNOVER_BANDS[j.turnoverBand], GROWTH_GOALS[j.growthGoal], ENTITY_TYPES[j.entityType], j.city ?? "", istDate(j.createdAt), j.createdBy,
    ]));
  addTableSheet(wb, "Documents",
    ["Client", "Job", "Doc type", "File name", "Uploaded by", "Uploaded on", "Link"],
    input.documents.map((d) => [d.client, d.job, DOC_TYPES[d.docType], d.name, d.uploadedBy, istDate(d.createdAt), d.webUrl]));
  return wb;
}

const who = (u: { name: string | null; email: string }) => u.name ?? u.email;

export async function loadWorkbookInput(): Promise<WorkbookInput> {
  const [clients, jobs, documents] = await Promise.all([
    prisma.client.findMany({
      orderBy: { name: "asc" },
      include: { primaryHandler: { select: { name: true, email: true } }, jobs: { select: { createdAt: true } } },
    }),
    prisma.job.findMany({
      orderBy: { createdAt: "desc" },
      include: {
        client: { select: { name: true, turnoverBand: true, growthGoal: true, entityType: true, city: true } },
        serviceType: true,
        handler: { select: { name: true, email: true } },
        createdBy: { select: { name: true, email: true } },
      },
    }),
    prisma.clientDocument.findMany({
      orderBy: { createdAt: "desc" },
      include: {
        client: { select: { name: true } },
        job: { select: { fy: true, serviceType: { select: { name: true } } } },
        uploadedBy: { select: { name: true, email: true } },
      },
    }),
  ]);
  return {
    clients: clients.map((c) => ({
      name: c.name, entityType: c.entityType, pan: c.pan, gstin: c.gstin, cin: c.cin, industry: c.industry, city: c.city,
      contactName: c.contactName, contactPhone: c.contactPhone, contactEmail: c.contactEmail, referralSource: c.referralSource,
      turnover: c.turnover, turnoverBand: c.turnoverBand, growthGoal: c.growthGoal, growthNote: c.growthNote, onboardedOn: c.onboardedOn,
      handler: who(c.primaryHandler), active: c.active, jobCount: c.jobs.length,
      lastJobOn: c.jobs.reduce<Date | null>((m, j) => (!m || j.createdAt > m ? j.createdAt : m), null), folderStatus: c.folderStatus,
    })),
    jobs: jobs.map((j) => ({
      client: j.client.name, fy: j.fy, department: j.serviceType.department, service: j.serviceType.name, handler: who(j.handler),
      status: j.status, dueOn: j.dueOn, fees: j.fees, turnoverBand: j.client.turnoverBand, growthGoal: j.client.growthGoal,
      entityType: j.client.entityType, city: j.client.city, createdAt: j.createdAt, createdBy: who(j.createdBy),
    })),
    documents: documents.map((d) => ({
      client: d.client.name, job: d.job ? `${d.job.fy} · ${d.job.serviceType.name}` : "KYC", docType: d.docType, name: d.name,
      uploadedBy: who(d.uploadedBy), createdAt: d.createdAt, webUrl: d.webUrl,
    })),
  };
}

export async function rebuildClientWorkbook(): Promise<{ ok: boolean; error?: string }> {
  const d = process.env.GRAPH_DRIVE_ID;
  const t = await getAppOnlyToken();
  if (!d || !t) return { ok: false, error: "Graph not configured (GRAPH_DRIVE_ID / MS_* env)" };
  try {
    const wb = buildClientWorkbook(await loadWorkbookInput());
    const bytes = new Uint8Array(await wb.xlsx.writeBuffer());
    await ensureFolder(d, "", clientsRoot(), t);
    await ensureFolder(d, clientsRoot(), "_Database", t);
    await uploadFileContent(d, WORKBOOK_PATH(), bytes, XLSX_MIME, t);
    return { ok: true };
  } catch (e) {
    console.error("client workbook rebuild failed:", (e as Error).message);
    return { ok: false, error: (e as Error).message };
  }
}

let timer: ReturnType<typeof setTimeout> | null = null;
// ponytail: in-process debounce — Railway runs one instance. If that changes, replace with
// a "dirty" flag in Settings and let the cron do the rebuild.
export function scheduleWorkbookRebuild(delayMs = 30_000): void {
  if (timer) clearTimeout(timer);
  timer = setTimeout(() => {
    timer = null;
    void rebuildClientWorkbook();
  }, delayMs);
}
